### ISSUE TITLE
issue running gulp for first time 

### ISSUE THREAD

**Issue by goelrohan6** [Grasia/teem#364]
I executed npm and bower install, after running gulp it showed this,

> [11:17:46] Using gulpfile ~/Documents/gsoc2017/berkman/teem/gulpfile.js
[11:17:46] Starting 'default'...
[11:17:46] Starting 'build'...
[11:17:46] Starting 'clean'...
[11:17:46] Finished 'clean' after 23 ms
[11:17:46] Starting 'html'...
[11:17:46] Starting 'fonts'...
[11:17:46] Starting 'l10n'...
[11:17:46] Starting 'images'...
[11:17:46] Starting 'sass'...
[11:17:46] Finished 'sass' after 6.07 ms
[11:17:46] Starting 'js'...
[11:17:46] Starting 'js:app'...
[11:17:46] Starting 'js:widgets'...
[11:17:46] Starting 'cordova'...
[11:17:48] Finished 'js:widgets' after 2.21 s
[11:17:52] Finished 'l10n' after 6.56 s
[11:17:58] Finished 'html' after 13 s
[11:18:01] Finished 'cordova' after 15 s
[11:18:04] Finished 'fonts' after 18 s
(node) util.error is deprecated. Use console.error instead.
WARN: Couldn't figure out mapping for ?:858,7 → 1,22375 []
WARN: Couldn't figure out mapping for ?:912,3 → 1,22674 []
WARN: Couldn't figure out mapping for ?:19607,10 → 6,6742 []
WARN: Couldn't figure out mapping for ?:20856,6 → 6,9199 []
WARN: Couldn't figure out mapping for ?:30128,10 → 7,18570 []
WARN: Couldn't figure out mapping for ?:31972,12 → 7,28686 []
WARN: Couldn't figure out mapping for ?:31977,10 → 7,28713 []
WARN: Couldn't figure out mapping for ?:33800,8 → 8,4059 []
WARN: Couldn't figure out mapping for ?:90941,14 → 26,13644 []
WARN: Couldn't figure out mapping for ?:100204,0 → 30,13251 []
WARN: Couldn't figure out mapping for ?:100204,18 → 30,13270 []
WARN: Couldn't figure out mapping for ?:100204,29 → 30,13279 []
WARN: Couldn't figure out mapping for ?:100204,39 → 30,13288 []
WARN: Couldn't figure out mapping for ?:103103,10 → 31,17202 []
WARN: Couldn't figure out mapping for ?:103108,12 → 31,17239 []
WARN: Couldn't figure out mapping for ?:103937,2 → 31,29275 []
WARN: Couldn't figure out mapping for ?:103937,20 → 31,29278 []
WARN: Couldn't figure out mapping for ?:103937,31 → 31,29287 []
WARN: Couldn't figure out mapping for ?:105467,4 → 33,991 []
WARN: Couldn't figure out mapping for ?:105467,20 → 33,1005 []
WARN: Couldn't figure out mapping for ?:105468,2 → 33,1162 []
WARN: Couldn't figure out mapping for ?:105468,16 → 33,1165 []
WARN: Couldn't figure out mapping for ?:105468,27 → 33,1174 []
WARN: Couldn't figure out mapping for ?:105468,37 → 33,1183 []
WARN: Couldn't figure out mapping for ?:105468,49 → 33,1194 []
WARN: Couldn't figure out mapping for ?:105468,63 → 33,1207 []
WARN: Couldn't figure out mapping for ?:105537,4 → 33,2131 []
WARN: Couldn't figure out mapping for ?:105537,29 → 33,2154 []
WARN: Couldn't figure out mapping for ?:105538,2 → 33,2307 []
WARN: Couldn't figure out mapping for ?:105538,25 → 33,2310 []
WARN: Couldn't figure out mapping for ?:105538,36 → 33,2319 []
WARN: Couldn't figure out mapping for ?:105538,46 → 33,2328 []
WARN: Couldn't figure out mapping for ?:105538,58 → 33,2339 []
WARN: Couldn't figure out mapping for ?:105538,72 → 33,2352 []
[11:19:00] Finished 'js:app' after 1.23 min
[11:19:00] Finished 'js' after 1.23 min
[11:19:05] gulp-imagemin: Minified 68 images (saved 751 kB - 5.1%)
[11:19:05] Finished 'images' after 1.32 min
[11:19:05] Finished 'build' after 1.32 min
[11:19:05] Starting 'docker:swellrt'...
[11:19:05] Starting 'connect'...
[11:19:05] Finished 'connect' after 343 ms
[11:19:05] Starting 'watch'...
[11:19:05] Finished 'watch' after 16 ms
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn docker-compose ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)

**Comment by suvigyavijay** [comment]
You haven't installed `docker-compose`. In case you have, please logout and log in again to proceed.

> You can use Docker (v1.9.x) to have SwellRT running. SwellRT is a real-time federated collaboration framework, which is installed and executed automatically by Teem though Docker.
> 
> Add your user into the docker group to have the necessary permissions. In GNU/Linux, try:
> 
> `wget -qO- https://get.docker.com/ | sh`
> `sudo usermod -aG docker <your_user>`
> And then restart your computer.
> 
> Finally, you also need Docker Compose to set up the development environment. Follow the instructions at Install Docker Compose

**Comment by goelrohan6** [comment]
@suvigyavijay i installed docker-comose in my pc, and on running gulp getting an error again 

> [13:21:32] Finished 'fonts' after 31 s
(node) util.error is deprecated. Use console.error instead.
WARN: Couldn't figure out mapping for ?:858,7 → 1,22375 []
WARN: Couldn't figure out mapping for ?:912,3 → 1,22674 []
WARN: Couldn't figure out mapping for ?:19607,10 → 6,6742 []
WARN: Couldn't figure out mapping for ?:20856,6 → 6,9199 []
WARN: Couldn't figure out mapping for ?:30128,10 → 7,18570 []
WARN: Couldn't figure out mapping for ?:31972,12 → 7,28686 []
WARN: Couldn't figure out mapping for ?:31977,10 → 7,28713 []
WARN: Couldn't figure out mapping for ?:33800,8 → 8,4059 []
WARN: Couldn't figure out mapping for ?:90941,14 → 26,13644 []
WARN: Couldn't figure out mapping for ?:100204,0 → 30,13251 []
WARN: Couldn't figure out mapping for ?:100204,18 → 30,13270 []
WARN: Couldn't figure out mapping for ?:100204,29 → 30,13279 []
WARN: Couldn't figure out mapping for ?:100204,39 → 30,13288 []
WARN: Couldn't figure out mapping for ?:103181,10 → 31,18554 []
WARN: Couldn't figure out mapping for ?:103186,12 → 31,18591 []
WARN: Couldn't figure out mapping for ?:104015,2 → 31,30627 []
WARN: Couldn't figure out mapping for ?:104015,20 → 31,30630 []
WARN: Couldn't figure out mapping for ?:104015,31 → 31,30639 []
WARN: Couldn't figure out mapping for ?:105467,4 → 33,991 []
WARN: Couldn't figure out mapping for ?:105467,20 → 33,1005 []
WARN: Couldn't figure out mapping for ?:105468,2 → 33,1162 []
WARN: Couldn't figure out mapping for ?:105468,16 → 33,1165 []
WARN: Couldn't figure out mapping for ?:105468,27 → 33,1174 []
WARN: Couldn't figure out mapping for ?:105468,37 → 33,1183 []
WARN: Couldn't figure out mapping for ?:105468,49 → 33,1194 []
WARN: Couldn't figure out mapping for ?:105468,63 → 33,1207 []
WARN: Couldn't figure out mapping for ?:105537,4 → 33,2131 []
WARN: Couldn't figure out mapping for ?:105537,29 → 33,2154 []
WARN: Couldn't figure out mapping for ?:105538,2 → 33,2307 []
WARN: Couldn't figure out mapping for ?:105538,25 → 33,2310 []
WARN: Couldn't figure out mapping for ?:105538,36 → 33,2319 []
WARN: Couldn't figure out mapping for ?:105538,46 → 33,2328 []
WARN: Couldn't figure out mapping for ?:105538,58 → 33,2339 []
WARN: Couldn't figure out mapping for ?:105538,72 → 33,2352 []
[13:22:28] Finished 'js:app' after 1.47 min
[13:22:28] Finished 'js' after 1.47 min
[13:22:34] gulp-imagemin: Minified 68 images (saved 751 kB - 5.1%)
[13:22:34] Finished 'images' after 1.55 min
[13:22:34] Finished 'build' after 1.55 min
[13:22:34] Starting 'docker:swellrt'...
[13:22:34] 'docker:swellrt' errored after 25 ms
[13:22:34] Error: spawn EACCES
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at dockerSwellrt (/home/rohan/Documents/gsoc2017/berkman/teem/gulpfile.js:599:15)
    at Gulp.<anonymous> (/home/rohan/Documents/gsoc2017/berkman/teem/gulpfile.js:624:3)
    at module.exports (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/run-sequence/index.js:64:16)
    at Gulp.onTaskEnd (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/run-sequence/index.js:53:5)
    at emitOne (events.js:95:20)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/index.js:264:8)
    at /home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/index.js:275:23
    at finish (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/lib/runTask.js:21:8)
[13:22:34] 'default' errored after 1.55 min
[13:22:34] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:95:20)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/index.js:264:8)
    at /home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/index.js:275:23
    at finish (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/run-sequence/index.js:45:4)
    at emitOne (events.js:95:20)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/index.js:264:8)
    at /home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/index.js:275:23
    at finish (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/home/rohan/Documents/gsoc2017/berkman/teem/node_modules/orchestrator/lib/runTask.js:36:10)

**Comment by atfornes** [comment]
It Seems like a permissions problem: ```[13:22:34] Error: spawn EACCES```

Please, make sure your user is in the docker group as explained in our README:

> Add your user into the docker group to have the necessary permissions. In GNU/Linux, try:
>
> wget -qO- https://get.docker.com/ | sh
> sudo usermod -aG docker <your_user>

**Comment by goelrohan6** [comment]
@atfornes i did execute the above `sudo usermod -aG docker <your_user>` command but am still facing the issue !

**Comment by atfornes** [comment]
Please @goelrohan6, could you double check that your user is in docker group by executing ```groups``` and checking that docker is one of your user groups?

Thanks

**Comment by goelrohan6** [comment]
@atfornes solved with above errors and encountered some more of them 

here's my console after opening localhost:8000

![image](https://cloud.githubusercontent.com/assets/14099191/23571061/248d532a-008d-11e7-89bc-db3382a41e10.png)

**Comment by divyanshu-rawat** [comment]
@goelrohan6 Have you restarted your computer after installing Docker ? if not then restart it .

**Comment by goelrohan6** [comment]
@divyanshu-rawat yes i did, its still the same !

**Comment by divyanshu-rawat** [comment]
@goelrohan6 I was also facing the same issue but after restarting my PC it started working.
Still, I am getting one error in the console but not getting those to warnings in terminal.
Just Google it, Hope you will find something useful.
Or try setting up everything from scratch I think you missed something

**Comment by goelrohan6** [comment]
@divyanshu-rawat @atd , i found the solution there, and a problem occured,

![image](https://cloud.githubusercontent.com/assets/14099191/23578249/801ae8a4-00f8-11e7-9b35-a99352e55fd2.png)

i executed `DOCKER_API_VERSION=1.22` and the version still remains the same

![image](https://cloud.githubusercontent.com/assets/14099191/23578311/15f8d18c-00fa-11e7-8b0a-8fed7184773b.png)

**Comment by divyanshu-rawat** [comment]
@goelrohan6  Try installing the lower version of Docker.
I think you need to downgrade Docker version to overcome the problem.

**Comment by goelrohan6** [comment]
@divyanshu-rawat can you tell me which version you are using so that i can downgrade it till there !

**Comment by divyanshu-rawat** [comment]
@goelrohan6 
Client:
 Version:      17.03.0-ce
 API version:  1.26

**Comment by divyanshu-rawat** [comment]
try this export COMPOSE_API_VERSION=1.18

**Comment by goelrohan6** [comment]
@divyanshu-rawat i uninstalled docker completely :(, have to do the whole thing again

**Comment by divyanshu-rawat** [comment]
@goelrohan6 oh okay just give it a try once again.

**Comment by goelrohan6** [comment]
Finally i did it :dancer:
